# Generated by Django 3.1.2 on 2020-10-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='slug')),
                ('description', models.TextField(null=True, verbose_name='description')),
            ],
        ),
    ]
